### ISSUE TITLE
Highlight color was lost in the last update

### ISSUE THREAD

**Issue by DeusAbel** [sourcechord/FluentWPF#76]
The highlight color is now a dark color whatever the system color, with the previous version this does not happen.

Net. CORE 3

**Comment by sourcechord** [comment]
Hi, @DeusAbel

Thanks for the feedback.
I couldn't understand this issue.

Please show me more information.
What code are you trying to?

**Comment by DeusAbel** [comment]
> 
> 
> Hi, @DeusAbel
> 
> Thanks for the feedback.
> I couldn't understand this issue.
> 
> Please show me more information.
> What code are you trying to?

![imagen](https://user-images.githubusercontent.com/22154122/68073585-b8766c80-fd5f-11e9-9bc4-d25991d1d004.png)

This border effect doesn't work. Now the border is solid dark color

**Comment by sourcechord** [comment]
Thanks for the information.

What version are you using?
Stable version of FluentWPF is 0.7.0.
And now, latest preview version(FluentWPF 0.8.0-alphaXXX) is under construction.
I'm adjusting the params of reveal effects.

**Comment by sourcechord** [comment]
Hi, @DeusAbel
It was fixed in [FluentWPF 0.8.0](https://github.com/sourcechord/FluentWPF/releases/tag/v0.8.0).
I'll close this issue.
If you have any problems, please reopen this issue.

**Comment by DeusAbel** [comment]
mmm there were improvements in the latest update, but the highcolor border still continues not to be like this image 
![imagen](https://user-images.githubusercontent.com/22154122/69094931-4ff5e380-0a1f-11ea-9c00-d878f4b4e9f5.png)

**Comment by sourcechord** [comment]
Current behavior is by design, and is reflected recent styles of Windows10's Fluent Design.
I'm still updating and refining the reveal effects of Windows10.

Please tell me, if you have any troubles with FluentWPF's design.
